nextcloud:
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  host: nextcloud.local
  username: admin
  password: adminpassword

redis:
  enabled: true
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false

postgresql:
  enabled: false

externalDatabase:
  enabled: false

persistence:
  enabled: false
