apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m0s
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud-repo
        namespace: flux-system
      version: "1.0.0"
  values:
    nextcloud:
      host: nextcloud.local
      username: admin
      password: adminpassword
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
    postgresql:
      enabled: false
    externalDatabase:
      enabled: false
    persistence:
      enabled: false
