apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: nextcloud
spec:
  interval: 1h0m0s
  type: oci  
  url: oci://ghcr.io/weaveworks/charts

